

#Setting the logging levels for the service
logging:
  level:
    root: debug


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 8902

security:
  oauth2:
    #client:
      #client-id: userService
      #client-secret: 123456
      #scope: webclient
    resource:
      token-info-uri: http://localhost:8901/auth/user
      #token-info-uri: http://localhost:8901/auth/user
