server:
  port: 7071
logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    path: "./logs/"
  file.max-size: 10MB
  level:
    org.hibernate.SQL: TRACE
    org.hibernate.type.description.sql: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        order_inserts: true
        dialect: com.zgy.handle.cardservice.config.hibernate.CustomMySqlDialect
        jdbc:
          batch_size: 8
        #integrator_provider: com.zgy.handle.userService.service.auto.InsertEventIntegratorProvider
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.zgy.handle.cardservice.config.hibernate.CardNamingStrategy
    open-in-view: false
  datasource:
    url: jdbc:mysql://rm-2zen9dnoix990kl44fo.mysql.rds.aliyuncs.com:3306/system?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: zgy
    password: zgy@1234
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 5
    max-wait: 10000
    min-idle: 2
    initial-size: 2
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
  cache:
    type: redis
    redis:
      host: 192.168.31.12
      port: 6379