server:
  port: 6666
  ssl:
    key-store-type: PKCS12
    key-store: classpath:handlesystem.p12
    key-alias: handlesystem
    enabled: true
    key-store-password: handlesystem
jwt:
  secret: zgySecret
mj:
  token: Bear xxx