#Setting the logging levels for the service
logging:
  level:
    root: debug

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  servlet:
    context-path: /auth
  port: 8901

security:
  oauth2:
    resource:
      filter-order: 3
