server:
  port: 5555
logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    path: "./logs/gateWay/"
  file.max-size: 10MB
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.description.sql: TRACE
jwt:
  secret: zgySecret
mj:
  token: Bear xxx